name: Scrape

on:
  schedule:
    - cron: "6 0,3,12,15,18,21 * * *" # Run at 7pm,10pm,7am,10am,1pm,4pm and 6th minute Central
  workflow_dispatch:

env:
  HEARING_ID: "17819"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: dschep/install-pipenv-action@v1

      - run: pipenv sync

      - run: |
          pipenv run python scripts/scrape.py $HEARING_ID > data/$HEARING_ID.csv

      - run: |
          git add data/*
          git commit -m "Update data with Github Action"
          git push
